% Script for building of block S-function
display('Building PumpControlBlock S-function MEXW32')
mex -DOS_WIN ...
	-DENDIAN_LITTLE ...
	-DPROC_X86 ...
	-DDLL_EXPORT_INTERFACE ...
	-DSIMULINK_SIMULATION ...
	-IW:\FuelLibrary\WrightSolver ...
	-IW:\FuelLibrary ...
    -IW:\FuelLibrary\Common_Generic ...
	-IW:\FuelLibrary\Common ...
    -IW:\FuelLibrary\WrightSolver\DiodeControlBlock ...
	W:\FuelLibrary\PumpControlBlock\PumpControlBlockWrapper.c ...
	W:\FuelLibrary\PumpControlBlock\PumpControlBlock.c
