% Script for building of block S-function
display('Building OrifaceControlBlock S-function MEXW32')
mex -DOS_WIN ...
	-DENDIAN_LITTLE ...
	-DPROC_X86 ...
	-DDLL_EXPORT_INTERFACE ...
	-DSIMULINK_SIMULATION ...
	-IW:\FuelLibrary ...
	-IW:\FuelLibrary\Common_Generic ...
	W:\FuelLibrary\OrifaceControlBlock\OrifaceControlBlockWrapper.c ...
	W:\FuelLibrary\OrifaceControlBlock\OrifaceControlBlock.c
