% Script for building of block S-function
mex -g ...
   -DOS_WIN ...
	-DENDIAN_LITTLE ...
	-DPROC_X86 ...
	-DDLL_EXPORT_INTERFACE ...
	-DSIMULINK_SIMULATION ...
   -DLEGACY_UNIVERSAL_TIME ...
   -DDEBUG_PRINT ...
   -IT:\Dev\Models\Fsp_Generic\InletControlBlock ...
	-IT:\Dev\Models\Fsp_Generic ...
	-IT:\Dev\Models\Fsp_Generic\WrightSolver ...
	-IT:\Dev\Common_Generic ...
   -IT:\Dev\Models\Fsp ...
   T:\Dev\Models\Fsp_Generic\InletControlBlock\InletControlBlockWrapper.c ...
   T:\Dev\Common_Generic\GenericTypes.c ...
   T:\Dev\Common_Generic\PlatformFuncs.c ...
   T:\Dev\Models\Fsp_Generic\FspSignals.c ...
   T:\Dev\Common_Generic\Signals.c ...
   T:\Dev\Models\Fsp_Generic\FspUtils.c ...
   T:\Dev\Models\Fsp_Generic\WrightSolver\WrightSolver.c ...
   T:\Dev\Common_Generic\Utils.c ...
   T:\Dev\Common_Generic\Instrumentation.c ...
   T:\Dev\Common_Generic\UnivTime.c ...
	T:\Dev\Models\Fsp_Generic\InletControlBlock\InletControlBlock.c
% ref to -IT:\Dev\Models\Fsp only introduced for ExtIntH.inc and ExtIntC.inc
% Why is this circular dependency required?